builds:
  - main: ./cmd/forge
    ldflags:
      - -s -w -X github.com/frantjc/forge.Version={{ .RawVersion }} -X github.com/frantjc/forge.Prerelease={{ .Prerelease }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
