name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - run: make dl
      - run: make test
      - run: make build
      - name: 4ge use remote
        run: ./bin/4ge use frantjc/forge/testdata/actions/mock@main
      - name: 4ge use local
        run: ./bin/4ge use ./testdata/actions/mock
      - name: 4ge get resource
        run: ./bin/4ge get mock
      - name: 4ge prune
        run: ./bin/4ge prune
