name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true
      - run: make dl
      - uses: golangci/golangci-lint-action@v3.3.1
      - run: make test
      - uses: goreleaser/goreleaser-action@v3
        with:
          install-only: true
      - name: make install
        run: make install INSTALL=install BIN=$RUNNER_TEMP
      - name: set path
        run: echo $RUNNER_TEMP >> $GITHUB_PATH
      - name: forge use remote
        run: forge use frantjc/forge/testdata/actions/mock/docker@main
      - name: forge use local
        run: forge use ./testdata/actions/mock/node
      - name: forge use dockerfile
        run: forge use ./testdata/actions/mock/dockerfile
      - name: forge check resource
        run: forge check mock -i version=v0.0.0
      - name: forge get resource
        run: forge get mock -i version=v0.0.0
      - name: forge put resource
        run: forge put mock -i version=v0.0.0
      - run: forge prune
