name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - run: make dl
      - run: make test
      - uses: goreleaser/goreleaser-action@v3
        with:
          install-only: true
      - name: make install
        run: make install INSTALL=install BIN=$RUNNER_TOOL_CACHE
      - name: path
        run: echo $RUNNER_TOOL_CACHE >> $GITHUB_PATH
      - name: forge use remote
        run: forge use frantjc/forge/testdata/actions/mock@main
      - name: forge use local
        run: forge use ./testdata/actions/mock
      - name: forge get resource
        run: forge get mock
      - run: forge prune
