name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20.
          cache: true
      - run: make dl
      - uses: golangci/golangci-lint-action@v3.4.0
      - run: make test
      - uses: goreleaser/goreleaser-action@v4
        with:
          install-only: true
      - name: Run make install
        run: make i INSTALL=install BIN=$RUNNER_TEMP
      - name: Set path
        run: echo $RUNNER_TEMP >> $GITHUB_PATH
      - name: Run forge use remote
        run: forge use frantjc/forge/testdata/actions/docker@${{ github.ref_name }}
      - name: Run forge use local
        run: forge use ./testdata/actions/node
      - name: Run forge use dockerfile
        run: forge use ./testdata/actions/dockerfile
      - name: Run forge check resource
        run: forge check mock -V version=v0.0.0
      - name: Run forge get resource
        run: forge get mock -V version=v0.0.0
      - name: Run forge put resource
        run: forge put mock -V version=v0.0.0 -p version=v0.0.0
      - run: forge prune
